"use client";
import { useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { Network,Search } from "lucide-react";
import Layout from "@/components/layout/Layout";
import ProgressiveKnowledgeGraph from "@/components/knowledge-graph/ProgressiveKnowledgeGraph";
export default function KnowledgeGraphPage(){const {orgId}=useParams();const router=useRouter();const [q,setQ]=useState("");const [results,setResults]=useState([]);const [data,setData]=useState({nodes:[],edges:[]});const [loading,setLoading]=useState(false);const [includeSuggested,setIncludeSuggested]=useState(false);const [relationshipType,setRelationshipType]=useState("");
 async function search(e){e?.preventDefault();setLoading(true);const r=await fetch(`/api/org/${orgId}/knowledge-graph?q=${encodeURIComponent(q)}`);const j=await r.json();setResults(j.nodes||[]);setLoading(false)}
 async function expand(n){setLoading(true);const sp=new URLSearchParams({start:n.id,depth:"2"});if(includeSuggested)sp.set("includeSuggested","1");if(relationshipType)sp.set("relationshipType",relationshipType);const r=await fetch(`/api/org/${orgId}/knowledge-graph?${sp}`);const j=await r.json();setData({nodes:j.nodes||[],edges:j.edges||[]});setResults([]);setLoading(false)}
 return <Layout orgId={orgId}><div className="mx-auto max-w-7xl space-y-5 p-6"><div><div className="flex items-center gap-2"><Network className="h-6 w-6 text-primary-600"/><h1 className="text-2xl font-bold">Organizational Knowledge Graph</h1></div><p className="mt-1 text-sm text-gray-500">Search first, then progressively explore trusted, inferred, conflict, and suggested knowledge connections.</p></div><form onSubmit={search} className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-lg border bg-white py-2.5 pl-9 pr-3 dark:bg-gray-900" placeholder="Search documents, topics, or entities"/></div><button className="rounded-lg bg-primary-600 px-4 text-white">Search</button></form><div className="flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={includeSuggested} onChange={e=>setIncludeSuggested(e.target.checked)} className="mr-2"/>Include suggested project links</label><select value={relationshipType} onChange={e=>setRelationshipType(e.target.value)} className="rounded border bg-white px-2 py-1 dark:bg-gray-900"><option value="">All relationship types</option><option value="shares_topic">Shares topic</option><option value="shares_entity">Shares entity</option><option value="related_to_project">Related to project</option><option value="related_to_lesson">Related to lesson</option><option value="conflict">Conflict</option></select></div>{loading&&<p className="text-sm text-gray-500">Loading…</p>}{results.length>0&&<div className="space-y-2"><p className="text-sm font-medium">Choose a starting node</p>{results.map(n=><button key={n.id} onClick={()=>expand(n)} className="mr-2 rounded-lg border px-3 py-2 text-sm hover:border-primary-400">{n.label} · {n.type}</button>)}</div>}{data.nodes.length>0&&<ProgressiveKnowledgeGraph nodes={data.nodes} edges={data.edges} onExpand={expand} onOpenDocument={n=>router.push(`/document?id=${n.entityId}`)}/>}</div></Layout>}
