import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";const read=p=>fs.readFileSync(p,"utf8");
test("14-A-D graph normalizes required nodes and provenance",()=>{const s=read("src/lib/knowledgeGraph.js");for(const t of ["document","project","topic","entity","expert","decision","lesson","department","explicit","inferred","conflict","suggested"])assert.match(s,new RegExp(`\\b${t}\\b`));assert.match(s,/TimelineEvent|timelineEvent/);});
test("14-B suggested links excluded unless explicitly requested",()=>{const s=read("src/lib/knowledgeGraph.js");assert.match(s,/link\.status===\"suggested\"&&!filters\.includeSuggested/);});
test("14-E-F traversal is bounded and RBAC occurs in service",()=>{const s=read("src/lib/knowledgeGraph.js");assert.match(s,/accessSql/);assert.match(s,/GRAPH_DEFAULT_DEPTH = 2/);assert.match(s,/GRAPH_NODE_LIMIT = 75/);assert.match(s,/Math\.min\(2/);assert.match(s,/Never emit dangling edges/);});
test("14-G graph UI is generate-first, scope-aware, insight-driven and sidebar reachable",()=>{const page=read("src/app/(app)/org/[orgId]/knowledge-graph/page.jsx"),side=read("src/components/layout/AppSidebar.jsx");assert.match(page,/Generate Graph/);assert.match(page,/Org-wide/);assert.match(page,/Dept-wise/);assert.match(page,/ProgressiveKnowledgeGraph/);assert.match(page,/Regenerate/);assert.match(side,/Knowledge Graph/);});

test("14-G expert edges render additive expertise scores without invalid percentages",()=>{const s=read("src/components/knowledge-graph/ProgressiveKnowledgeGraph.jsx");assert.match(s,/e\.type===["']expert_in["']/);assert.match(s,/expertise score/);});

test("14-G node selection does not navigate until explicit Open document action",()=>{const graph=read("src/components/knowledge-graph/ProgressiveKnowledgeGraph.jsx"),page=read("src/app/(app)/org/[orgId]/knowledge-graph/page.jsx");assert.match(graph,/onClick=\{\(\) => onSelect\(node\)\}/);assert.match(graph,/Open document/);assert.match(page,/onOpenDocument/);assert.match(page,/router\.push/);});
test("14-G insights are evidence-backed without automatic LLM generation",()=>{const graph=read("src/components/knowledge-graph/ProgressiveKnowledgeGraph.jsx"),page=read("src/app/(app)/org/[orgId]/knowledge-graph/page.jsx");assert.match(graph,/Why it is connected/);assert.match(graph,/edge\.evidence/);assert.match(page,/does not call an LLM/);});
